# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=120)),
                ('license_plate', models.CharField(max_length=120)),
                ('license_date', models.DateTimeField()),
                ('next_license_date', models.DateTimeField()),
                ('token_plate', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Job Detail',
                'verbose_name_plural': 'Job Details',
            },
        ),
    ]
